-- Quote Requests Table Setup for JLS Lawn Maintenance
-- Run this in Supabase SQL Editor to create the quote_requests table

-- Create the quote_requests table
CREATE TABLE IF NOT EXISTS public.quote_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  address text,
  service text,
  contact_method text,
  message text,
  status text DEFAULT 'new'
);

-- Enable Row Level Security (same pattern as jobs table)
ALTER TABLE public.quote_requests ENABLE ROW LEVEL SECURITY;

-- Create policy for open access (matching jobs table security)
CREATE POLICY "Enable all access for all users" 
ON public.quote_requests 
AS PERMISSIVE
FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Index for faster queries on status
CREATE INDEX IF NOT EXISTS quote_requests_status_idx ON public.quote_requests(status);

-- Index for created_at to sort by newest first
CREATE INDEX IF NOT EXISTS quote_requests_created_at_idx ON public.quote_requests(created_at DESC);
