-- Copy and paste this into the Supabase "SQL Editor" to set up your database!

-- 1. Create the 'jobs' table
create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_time text not null,     -- We'll store the date string here
  job_type text not null,       -- 'mowing' or 'hedge'
  notes text,                   -- Optional notes
  status text default 'pending' -- 'pending' or 'done'
);

-- 2. Turn off "Row Level Security" (RLS) for now
-- This makes it so anyone with your API Key can read/write. 
-- Since this is just a prototype for your family, this is the easiest way to start.
alter table public.jobs enable row level security;

create policy "Enable all access for all users"
on "public"."jobs"
as PERMISSIVE
for ALL
to public
using ( true )
with check ( true );
