-- Copy and paste this into the Supabase "SQL Editor" to set up your database!

-- 1. Create the 'jobs' table (FRESH INSTALL)
create table public.jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  start_time text not null,           -- We'll store the date string here
  job_type text not null,             -- 'mowing' or 'hedge'
  notes text,                         -- Optional notes
  status text default 'pending',      -- 'pending', 'done', or 'cancelled'
  price numeric,                      -- Job price
  address text,                       -- Job location address
  client_phone text,                  -- Client phone number for SMS
  recurring_id text,                  -- ID to link recurring jobs
  is_recurring boolean default false, -- Whether this is part of a recurring series
  recurrence_pattern text,            -- JSON pattern for recurrence
  occurrence_number int               -- Which occurrence number in the series
);

-- 2. Turn off "Row Level Security" (RLS) for now
-- This makes it so anyone with your API Key can read/write. 
-- Since this is just a prototype for your family, this is the easiest way to start.
alter table public.jobs enable row level security;

create policy "Enable all access for all users"
on "public"."jobs"
as PERMISSIVE
for ALL
to public
using ( true )
with check ( true );

-- ============================================================
-- MIGRATION SCRIPTS (Run these if you already have a 'jobs' table)
-- ============================================================

-- Run each of these one at a time if you're getting errors about missing columns:

-- Add price column
-- alter table public.jobs add column if not exists price numeric;

-- Add address column
-- alter table public.jobs add column if not exists address text;

-- Add phone column
-- alter table public.jobs add column if not exists client_phone text;

-- Add recurring job columns (THE NEW ONES!)
-- alter table public.jobs add column if not exists recurring_id text;
-- alter table public.jobs add column if not exists is_recurring boolean default false;
-- alter table public.jobs add column if not exists recurrence_pattern text;
-- alter table public.jobs add column if not exists occurrence_number int;
